<?php
/*
Plugin Name: Remove Category Base
Plugin URI: https://www.littlebizzy.com/plugins/remove-category-base
Description: Completely disables the category base from all URLs generated by WordPress so that there is no category slug displayed on archive permalinks, etc.
Version: 1.0.5
Author: LittleBizzy
Author URI: https://www.littlebizzy.com
License: GPLv3
License URI: http://www.gnu.org/licenses/gpl-3.0.html
Prefix: RVCTBS
*/

// Plugin namespace
namespace LittleBizzy\RemoveCategoryBase;

// Plugin constants
define('RVCTBS_FILE', __FILE__);
define('RVCTBS_PATH', dirname(RVCTBS_FILE));
define('RVCTBS_VERSION', '1.0.5');
const FILE = __FILE__;
const PREFIX = 'rvctbs';
const VERSION = '1.0.5';

// Block direct calls
if (!function_exists('add_action'))
	die;

// Admin Notices module
require_once dirname(FILE).'/admin-notices.php';
Admin_Notices::instance(FILE);

// Admin Notices Multisite module
// (uncomment //return to disable plugin on Multisite)
require_once dirname(FILE).'/admin-notices-ms.php';
if (false !== \LittleBizzy\RemoveCategoryBase\Admin_Notices_MS::instance(FILE)) {
	//return;
}

// Load main class
require_once dirname(FILE).'/core/core.php';
RVCTBS_Core::instance();

// Plugin hooks
register_activation_hook(__FILE__, array(RVCTBS_Core::instance(), 'activation'));
register_deactivation_hook(__FILE__, array(RVCTBS_Core::instance(), 'deactivation'));
